version: "3.1"

services:
  ssh-agent:
    build:
      context: .
      dockerfile: ssh.Dockerfile
    volumes:
      - ~/.ssh:/.ssh
      - ssh-sock:/.ssh-agent/

  service:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ssh-sock:/.ssh-agent/
      - /node_modules/
    environment:
      - SSH_AUTH_SOCK=/.ssh-agent/socket

volumes:
  ssh-sock:
